// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQnYUCP9FE17z06J5bDvjOinZ2Yf20-f0',
    appId: '1:585764065217:web:be2a2af7cccaf2d804a940',
    messagingSenderId: '585764065217',
    projectId: 'e-commerceapp-b77cf',
    authDomain: 'e-commerceapp-b77cf.firebaseapp.com',
    storageBucket: 'e-commerceapp-b77cf.appspot.com',
    measurementId: 'G-D3XSQPVLWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiXk7C5WrwC4WsPo1o5qLSimS6H9gOmaY',
    appId: '1:585764065217:android:6f8e64caf92c956304a940',
    messagingSenderId: '585764065217',
    projectId: 'e-commerceapp-b77cf',
    storageBucket: 'e-commerceapp-b77cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuKZtyr0Gbcsx_BvOmxDt2ZbigY57HRPQ',
    appId: '1:585764065217:ios:3aa8a589b8f2a8d304a940',
    messagingSenderId: '585764065217',
    projectId: 'e-commerceapp-b77cf',
    storageBucket: 'e-commerceapp-b77cf.appspot.com',
    androidClientId: '585764065217-u87dkifd24fdtlpjdn75h7ktaof6ci2v.apps.googleusercontent.com',
    iosClientId: '585764065217-fft6guh3bhed68sfje3umq7f362lg57i.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuKZtyr0Gbcsx_BvOmxDt2ZbigY57HRPQ',
    appId: '1:585764065217:ios:53d8afb2b6765efc04a940',
    messagingSenderId: '585764065217',
    projectId: 'e-commerceapp-b77cf',
    storageBucket: 'e-commerceapp-b77cf.appspot.com',
    androidClientId: '585764065217-u87dkifd24fdtlpjdn75h7ktaof6ci2v.apps.googleusercontent.com',
    iosClientId: '585764065217-4eisi0ge0i8orii3u2t11bltsufufe7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
